# Default values for hyprscreend-cpp
# hyprscreend.conf 2026 (c) Nitrux Latinoamericana S.C.

[General]
HyprConfig="$HOME/.config/hypr/hyprland.lua"
ScaleFactor=1.0

[Screens]
InternalScreen="eDP-1"
ExternalScreen=""
